image: markhobson/maven-chrome:jdk-8

stages:
  - prepare 

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

prepare:
  stage: prepare
  script: 
    - wipCommits=`git log -1 --pretty=%B`; if [$wipCommits="invoice"]; then echo "WIP commits detected; aborting."; exit 1; fi
    - echo "success"	
    - mvn compile
    - mvn test -Dtest=com.eliasnogueira.wdm.GithubWDMPageTest

prepare:
  stage: prepare
  script: 
    - wipCommits=`git log -1 --pretty=%B`; if [$wipCommits="ippayments"]; then echo "WIP commits detected; aborting."; exit 1; fi
    - echo "success"	
    - mvn compile
    - mvn test -Dtest=com.eliasnogueira.wdm.GithubWDMPageTest2
