image: markhobson/maven-chrome:jdk-8

stages:
  - build 
  - prepare 

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  tags:
    - zalenium
  script:
    - mvn compile
    - docker pull elgalu/selenium
    - docker pull dosel/zalenium
    - docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start

prepare1:
  stage: prepare
  tags:
    - zalenium
  script: 
    - wipCommits=`git log -1 --pretty=%B`;module="invoice"; if [[ $wipCommits == $module ]]; then mvn clean test -Dsurefire.suiteXmlFiles=GithubWDMPageTest.xml; fi	
    - wipCommits=`git log -1 --pretty=%B`;module="ippayments"; if [[ $wipCommits == $module ]]; then mvn clean test -Dsurefire.suiteXmlFiles=GithubWDMPageTest2.xml; fi
    - echo "Successfully executed"
