image: markhobson/maven-chrome:jdk-8

before_script:
  - docker pull elgalu/selenium
  - docker pull dosel/zalenium
  - docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start  

stages:
  - build
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test -Dtest=com.eliasnogueira.wdm.GithubWDMPageTest
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
