image: markhobson/maven-chrome:jdk-8

stages:
  - prepare 
  - prepare2

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

prepare1:
  stage: prepare
  script: 
    - wipCommits=`git log -1 --pretty=%B`;module="invoice"; if [[ $wipCommits == $module ]]; then echo "success invoice"; else echo "WIP commits detected; aborting."; exit 1; fi
    - echo "success "	
    - mvn compile
    - mvn test -Dtest=com.eliasnogueira.wdm.GithubWDMPageTest

prepare2:
  stage: prepare2
  script: 
    - wipCommits='git log -1 --pretty=%B'; if [$wipCommits=="ippayments"]];  then echo "success ippayments" else echo "WIP commits detected; aborting."; exit 1; fi
    - echo "success"	
    - mvn compile
    - mvn test -Dtest=com.eliasnogueira.wdm.GithubWDMPageTest2
